#!/bin/bash

SCRIPT=`realpath -s $0`
SCRIPTPATH=`dirname $SCRIPT`
fichierLog=$SCRIPTPATH/.log

fileSystem1=$SCRIPTPATH/$1
fileSystem2=$SCRIPTPATH/$2

cd $SCRIPTPATH

if [ $# -eq 2 ] # si on a entre 1 et 3 arguments sachant que arg0 = le script
then
	if [[ ! -e $fichierLog && $fileSystem2 =~ /home ]]
	then 
		rm -rf $fileSystem2
		cp -pr $fileSystem1 $fileSystem2
		echo "creation du ficher de synchronisation et mise a niveau des deux arbres "
		touch .log
		ls -lR $fileSystem1 | grep ^- > $fichierLog
		ls -lR $fileSystem1 | grep ^d >> $fichierLog
		echo "#1 $fileSystem1" >> $fichierLog
		echo "#2 $fileSystem2" >> $fichierLog
	else
		echo "le fichier synchro existe deja"
		source ./.functions/recursif $fileSystem1
		source ./.functions/recursif $fileSystem2
		ls -lR $fileSystem1 | grep ^- > $fichierLog
		ls -lR $fileSystem1 | grep ^d >> $fichierLog
		echo "#1 $fileSystem1" >> $fichierLog
		echo "#2 $fileSystem2" >> $fichierLog
	fi
elif [ $# -eq 0 ]
then
	if [[ ! -e $fichierLog ]]
	then
		echo "Le fichier des logs n'existe pas"
	else
		fileSystem1=`cat $fichierLog | grep "#1" | sed 's/#1 //'`
		fileSystem2=`cat $fichierLog | grep "#2" | sed 's/#2 //'`
		source ./.functions/recursif $fileSystem1
		cd $SCRIPTPATH
		source ./.functions/recursif $fileSystem2
		ls -lR $fileSystem1 | grep ^- > $fichierLog
		ls -lR $fileSystem1 | grep ^d >> $fichierLog
		echo "#1 $fileSystem1" >> $fichierLog
		echo "#2 $fileSystem2" >> $fichierLog	
	fi
else
	echo -e "Utilisation :\n 1) bash sychroniseur : synchronise avec les fichier présent dans les logs\n 2) bash synchroniseur \$1 \$2 Synchronise les 2 chemin passé en paramètre"
fi
