#!/bin/bash

#fonction qui a pour but de regarder dans un repertoire courant si les fichiers ont été modifié 
#si oui faire la synchronisation dans l'autre arbre et ecrire qu'il y a eu une modification dans le fichier journal 

function fonction_comp_f {
	file_from_other_three=`find ~ -type f -name $1 | grep "$2" `
	fichier1=`ls -l | grep $1 | sed 's/ *//g'` #le fichier du repertoire courant stocke dans la variable $fichier
        fichier2=`ls -l $file_from_other_three| grep $2 | sed 's/\/.*\///' | sed 's/ *//g'`  # la chaine de caractere ecrite dans le fichier .synchro 
#		echo "$fichier1"
#		echo "$fichier2"
	if [ "$fichier1" = "$fichier2" ] # on compare les deux chaines pour voir si il ya eu un changement 
		then
			return 0
		else
			return 1
	fi 
}
