#!/bin/bash
source ./.functions/comparaison_f
function parcours() {
if [ -d $1 ]
then
	cd $1
	for i in *;
	do
		parcours $i $2
	done
	cd ..
else
	echo $1
	fonction_comp_f $1 $2
	 echo "le resultat de la fonction = $?"
        if [ $? -eq 1 ] #C'est vrais = c'est different
        then
                echo "Les fichier sont differents"
        fi
fi
}

parcours $1 $2
