#!/bin/bash

function parcours() {
if [ -d $1 ]
then
	cd $1
	for i in *;
	do
		parcours $i
	done
	cd ..
else
	echo $1
	 echo "le resultat de la fonction = $?"
        if [ $? -eq 1 ] #C'est vrais = c'est different
        then
                echo "Les fichier sont differents"
        fi
fi
}

parcours $1
