#!/bin/bash

function fonction_comp_f {
	
	courant=`pwd`
	if [[ $courant =~ $fileSystem1 ]]
	then
		file_from_other_tree=`echo $1 | sed "s|$fileSystem1|$fileSystem2|g"`
	else
		file_from_other_tree=`echo $1 | sed "s|$fileSystem2|$fileSystem1|g"`
	fi
	
	fichier1=`ls -l $1 2>/dev/null | sed 's/ *//g' | cut -d/ -f1`
	fichier2=`ls -l $file_from_other_tree 2>/dev/null | sed 's/ *//g' | cut -d/ -f1`

	if [[ $fichier1 = $fichier2 ]]
	then
		return 0
	else
		return 1
	fi
}

function fonction_comp_d {

	cd $1	
	courant=`pwd`
	if [[ $courant =~ $fileSystem1 ]]
	then
		dir_from_other_tree=`echo $1 | sed "s|$fileSystem1|$fileSystem2|g"`
	else
		dir_from_other_tree=`echo $1 | sed "s|$fileSystem2|$fileSystem1|g"`
	fi
	dir1=`cat $1 2>&1 | cut -d: -f 3`
	dir2=`cat $dir_from_other_tree 2>&1 | cut -d: -f 3`
	if [[ $dir1 = $dir2 ]]
	then
		return 0
	else
		return 1
	fi
	cd ..

}
